#服务启动端口号。
server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /chat

spring:
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
  datasource:
    name: school
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

logging:
  level:
    com.dao: DEBUG
    org.springfromework.web: info
    eapp-corp-project: DEBUG
  file: ./logs/core.log
  root: DEBUG




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.model
